/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin(() => {
	const router = useRouter();
	const routesList = {
		about: "about",
		blogId: "blog-id",
		blog: "blog",
		experience: "experience",
		index: "index",
		projects: "projects",
	};

	return {
		provide: {
			typedRouter: router as TypedRouter,
			routesList,
		},
	};
});
