/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin((nuxtApp) => {
	const routesList = { about: "about", blog: "blog", experience: "experience", index: "index", projects: "projects" };

	return {
		provide: {
			typedRouter: nuxtApp.$router,
			routesList,
		},
	};
});
